PARAMETRI_ATTESI = [
    'CAR', 'TITOLO_MISURA', 'DES_TIPO_MISURA', 'COD_CE_MISURA', 'BASE_GIURIDICA_NAZIONALE',
    'LINK_TESTO_INTEGRALE_MISURA', 'IDENTIFICATIVO_UFFICIO', 'SOGGETTO_CONCEDENTE', 'COR',
    'TITOLO_PROGETTO', 'DESCRIZIONE_PROGETTO', 'LINK_TRASPARENZA_NAZIONALE', 'DATA_CONCESSIONE',
    'CUP', 'ATTO_CONCESSIONE', 'DENOMINAZIONE_BENEFICIARIO', 'CODICE_FISCALE_BENEFICIARIO',
    'DES_TIPO_BENEFICIARIO', 'REGIONE_BENEFICIARIO', 'ID_COMPONENTE_AIUTO', 'COD_PROCEDIMENTO',
    'DES_PROCEDIMENTO', 'COD_REGOLAMENTO', 'DES_REGOLAMENTO', 'COD_OBIETTIVO', 'DES_OBIETTIVO',
    'SETTORE_ATTIVITA', 'ELEMENTO_DI_AIUTO', 'IMPORTO_NOMINALE', 'DES_STRUMENTO', 'COD_STRUMENTO'
]
